server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Naren-18/medinfo-config.git
          default-label: docker
          clone-on-start: true
          force-pull: true